### PR TITLE
Add GitHub actions and the readme badge for running test when pull request

### PR DESCRIPTION
**Pull request by bw4sz**
# What does this PR do?
This commit adds github actions to run pytest for the v2.0 branch.

# Why?
Given the hard work you've put into this project, I want to make sure it remains as easy to maintain as possible. Plus I want to contribute where I can be useful. The repo already has unit tests, but they are not run on every pull request. Since we just confirmed that pytest is now fully reproducible, I've added a github actions workflow. To see an example, here is one of our projects:

https://github.com/weecology/DeepForest/actions

and the badge on the README

https://github.com/weecology/DeepForest

## Details

This tells any user that the current branch is up to date with tests and invites more contributions because it becomes more believable that it can be maintained over time. 

@henrykironde helped me set up our workflow and can help as well if needed. 

I've added a pytest.yml that should trigger on push and pull requests. I'm slighly worried about 3.2GB download, but I _think_ it will get cached (https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows), we can work on this if not. 

One small note, because I made the mistake on naming my first PR the v2.0 branch, when you merged those commits to your 2.0 branch, the commits of my first PR hang out in my history. Note that no changes are associated with these commits, since they are merged. After this PR I will delete my fork and re-fork.

### CODE REVIEW

**Comment by HowcanoeWang** [comment]
Thanks a lot for making this contribution, I will leave this PR for further discussion.

Before commiting, I run the pytest on my local machine every time. This non-reproducible problem is only caused by not updating the latest dataset in Google drive (and also the local Numpy versions).

To my understanding, the Action creates a new virtual envirnment each time to run the test code. But if is on a brand new environment, the pytest can not download the missing dataset automatically and raises FileNotFoundError in this case. 

So this online test workflow may not be suitable for the cache rule. It requires the dataset initialize step for everytime in the Action virtual machine, and needs downloads such data again and again.

Personally prefer contributor running the pytest on their local enviroment, just like what `scikit-learn` and `numpy` require for pull request.

Then I need to figure out the following items:

1. A solution to check the local dataset versions and support auto-update if it is out-of-date.
2. Edit the 5 tests depend on the 3.3GB `Lotus()` dataset, using the 300MB `TestData()` only to decrease the required dataset size for testing

**Comment by bw4sz** [comment]
Of course its up to you. Whatever you prefer. Just putting here that I configured it for my v2.0 fork branch and it ran in 7 minutes without error. I hear what you are saying about local checking though. 

https://github.com/bw4sz/EasyIDP/actions/runs/4560188172/jobs/8044901464

**Comment by bw4sz** [comment]
Confirming, I made a change to the README and it presumably read the cached datasets and ran pytest rapidly. So as long as you write a check for the last time the data was downloaded, it will atleast give you some coverage.

https://github.com/bw4sz/EasyIDP/actions/runs/4566623927/jobs/8059384271

You are welcome to close this PR if this is not a route you want to go, it wasn't much work for me. No pressure.

**Review by HowcanoeWang — APPROVED** [review]

**Comment by HowcanoeWang** [comment]
Thanks for this contribution, I will merge it when I removed the `Lotus()` dataset dependices in pytest #88

**Comment by bw4sz** [comment]
Sounds good, the only thing is that the html on the README for the badge isn't quite right. I thought it would be

```
<img alt="GitHub Actions Badge" src="https://github.com/github/docs/actions/workflows/pytest.yml/badge.svg?style=plastic">
```
I was following https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge, i tried with and without the ?style.

**Comment by HowcanoeWang** [comment]
The correct badge should be like:

```html
https://github.com/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE>/badge.svg
```

Has updated for this project: GitHub Actions Badge

```html
<img alt="GitHub Actions Badge" src="https://github.com/UTokyo-FieldPhenomics-Lab/EasyIDP/actions/workflows/pytest.yml/badge.svg?style=plastic">
```

**Pull request merged**
